version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo-portfolio2
    restart: unless-stopped
    ports:
      - "8080:80"  # Maps port 8080 on the host to port 80 in the container
    # If you need environment variables:
    # environment:
    #   - NODE_ENV=production